services:
  - type: web
    name: light-vpn
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: VLESS_UUID
        generateValue: true
      - key: PORT
        value: 10000
