services:
  - type: web
    name: light-vpn
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /ss-ws
    envVars:
      - key: SS_PASSWORD
        generateValue: true
      - key: PORT
        value: 10000
